### ISSUE TITLE
Automatic build and deploy to public host

### ISSUE THREAD

**Issue by lisachenko** [goaop/documentation#2]
It would be nice to configure automatic build of docs (for example, by Travis) and then just publish or deploy formatted docs to some host (GitHub pages?, Readthedocs?).

**Comment by lisachenko** [comment]
Ok, it's done.

For development host will be http://go-aop-php.readthedocs.io/en/dev/index.html until all docs will be ready to replace main docs.aopphp.com. Maybe, just move to aopphp.com domain directly? More conversion and tld domain should be cool.

@TheCelavi what is your opinion?

**Comment by TheCelavi** [comment]
Sorry for delayed response. I am having too much on my plate lately, so I have not been able to work on docs. docs.aopphp.com is good idea, me like it.

Current build has some issue accessing assets. I dont have access to a server, so you have to take care of it :)

**Comment by lisachenko** [comment]
Oh, don't excuse about being busy, it's your time and open-source is just hobby ) 

BTW, do you have an account on Readthedocs? If no then could you please register, I'll add you to the project admin to have control over it. Because I'm not sure what's wrong with assets, looks like they are missing in codebase.

**Comment by lisachenko** [comment]
> do you have an account on Readthedocs? If no then could you please register, I'll add you to the project admin to have control over it. Because I'm not sure what's wrong with assets, looks like they are missing in codebase.

Ping

**Comment by TheCelavi** [comment]
Here, swamped, sorry - will look into this for a weekend.

**Comment by lisachenko** [comment]
Ok, thanks, just register on readthedocs, so I'll be able to grant your admin access.

Probably, error is due to warning in build:
```
copying static files... WARNING: html_static_path entry u'/home/docs/checkouts/readthedocs.org/user_builds/go-aop-php/checkouts/dev/_static' does not exist
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
```

**Comment by TheCelavi** [comment]
All setup.

**Comment by lisachenko** [comment]
👍
